repo_url: https://github.com/gbevi/csl
repo_name: csl

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: Ruby to C Compiler

theme:
  name: material
  favicon: assets/img/favicon.png
  logo: assets/img/icon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/weather-night
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Claro

  language: pt-BR

extra_css: [assets/stylesheets/extra.css]

nav:
  - Home: index.md
  - Introdução: Introducao/Introducao.md
  - Estudo da Linguagem: Estudo/Estudo.md
  - Planejamento:
    - Escopo: Planejamento/Escopo.md
    - Cronograma: Planejamento/Cronograma.md
  - Resultados:
    - Resultados: Resultados/Resultados.md
    - Dificuldades: Dificuldades/Dificuldades.md
